services:
  - type: web
    name: daydreamer-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    autoDeploy: true
    region: oregon
    plan: free
